# --- ETAPA 1: Compilación ---
FROM golang:1.25-alpine AS builder

# Instalar git y certificados para dependencias
RUN apk add --no-cache git ca-certificates

WORKDIR /app

# Copiar archivos de módulos primero (aprovechar cache de Docker)
COPY go.mod go.sum ./
RUN go mod download

# Copiar el resto del código
COPY . .

# Compilar el binario optimizado (sin símbolos de debug para pesar menos)
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /app/api ./cmd/api/main.go

# --- ETAPA 2: Producción ---
FROM alpine:latest

# Instalar certificados (Crítico para que el SDK de AWS S3 funcione vía HTTPS)
RUN apk --no-cache add ca-certificates tzdata

# Creamos un usuario de sistema para no correr como root
RUN adduser -D -u 1000 clickuser
WORKDIR /app/

# Copiar solo el binario desde la etapa de compilación
COPY --from=builder /app/api .

# COPIAR LA CARPETA DE LOGOS (Si no está, el código dará error)
COPY assets ./assets 

# Cambiamos el dueño de la carpeta assets por si Go necesita escribir o leer con permisos
RUN chown -R clickuser:clickuser /app

USER clickuser

# Exponer el puerto
EXPOSE 8080

# Ejecutar
CMD ["./api"]